project:
  type: website
  output-dir: docs

website:
  title: "Kelly Morgan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    page-layout: full



